json.id            picture.id
json.title         picture.title
json.type          picture.media_type
json.created_at    picture.created_at
json.thumb_url     picture.image_thumb_url
json.big_url       picture.media_content_url
json.big_width     picture.media_content_width
json.big_height    picture.media_content_height
json.comments_size picture.comments_size_visible_by(current_user)
json.profile_id    picture.profile_id
json.vehicle_id    picture.vehicle_id
